### ISSUE TITLE
[Feature Request] Publish wheels for OS X and ARM64

### ISSUE THREAD

**Issue by Sitin** [pytorch/rl#1312]
It seems that the torchrl can run at arm64 and Apple Silicone. It would be nice to have the same requirements.txt/Pipfile at all platforms where this library can be executed.

**Comment by vmoens** [comment]
cc @osalpekar
How should we proceed to have this?

**Comment by osalpekar** [comment]
@Sitin @vmoens Wanted to clarify the ask here - IIUC all the wheels build requirements are explicitly listed here: https://github.com/pytorch/rl/blob/main/setup.py#L208, and are unified across platforms. Is the ask for official binaries for arm64/Apple Silicon?

**Comment by Sitin** [comment]
@osalpekar, just want to clarify. As @hyerra mentioned, while it is install pytorchlr on M1/M2 from the repository but I can't do the same using package version (i.e. `pip install torchrl`).

When it comes to the implementation, then platform-specific wheels with prebuilt binnaries would be my favorite options (and probably the easiest for you since CircleCI has M1 executors).

**Comment by osalpekar** [comment]
Thanks for clarifying. The issue is essentially that we don't publish first-party wheels for Apple Silicon or Arm64, but adding support is straightforward (at least for Apple Silicon). 

cc @atalman We should add Nova pipelines for TorchRL for M1, as well as for aarch64 once those are ready.

The reason the pip install works out of the box for Windows is that we are publishing wheels for Linux/Windows/Mac x86. The github link works since that seems to just check out the repo and build the wheel from source locally.

**Comment by Sitin** [comment]
@osalpekar, than you very much! Can't wait to finally fix my dependecy mess.

**Comment by vmoens** [comment]
v0.2.0 now includes wheels for M1!
Feel free to reopen if issues persist
