### ISSUE TITLE
[Question] What is ESS in PPO?

### ISSUE THREAD

**Issue by gitfourteen** [pytorch/rl#1708]
Here [ppo.py](https://github.com/pytorch/rl/blob/main/torchrl/objectives/ppo.py#L649) from PPO source code is the definition.
<img width="983" alt="Screenshot 2023-11-22 at 1 21 12 AM" src="https://github.com/pytorch/rl/assets/22335780/3ec3663e-7140-4353-a65a-8b13f761fab2">

Does ESS stand for **Effective Sample Size** or something else? 
What is the purpose logging this info?
A reference for 'ESS' would be helpful. Thank you.

**Comment by gitfourteen** [comment]
The `ESS` is indeed the **Effective Sample Size**, specifically for weighted i.i.d. observations. If replacing `log_weight` with `log_prob - prev_log_prob`, the equation of `ess` with `logsumexp' can reduce to the standard form as in this blog [What do we mean by effective sample size?](https://statisticaloddsandends.wordpress.com/2021/11/11/what-do-we-mean-by-effective-sample-size/)

**Comment by vmoens** [comment]
As you figured out, the ESS is the expected sample size. 
Since PPO is a derivation of importance sampling, we thought that having the ESS registered could give you an indication of how much the policy that you're training is differing from the one used for data collection during a training epoch.
If the two distributions match, the ESS is equal to the number of samples, but as they drift away, the ESS decreases. With PPO your ESS should never be too slow because it is "proximal", if it falls below a reasonable threshold (say, like your saturation, ie. normal is above 95%) you (or we, developer) should check that everything is fine.
