### ISSUE TITLE
[BUG] RuntimeError An attempt has been made to start a new process before the         current process has finished its bootstrapping phase

### ISSUE THREAD

**Issue by whatdhack** [pytorch/rl#1825]
## Describe the bug

Seeing the following on running torchrl_demo.py - similar to https://github.com/pytorch/rl/issues/1805 

## To Reproduce

Please use the markdown code blocks for both code and stack traces.

```python
python torchrl_demo.py
```

```bash
Traceback (most recent call last):
torchrl/tutorials/sphinx-tutorials/torchrl_demo.py", line 368, in <module>
    env.reset()
.
.
.
ib/python3.10/multiprocessing/spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.


  File ... 
```

## Expected behavior

No stacktrace

## Screenshots

N/A

## System info

Describe the characteristic of your environment:
 * Describe how the library was installed (pip, source, ...)
 * Python version 
 * Versions of any other relevant libraries

```python
import torchrl, numpy, sys
print(torchrl.__version__, numpy.__version__, sys.version, sys.platform)
0.2.1 1.26.1 3.10.13 (main, Sep 11 2023, 13:44:35) [GCC 11.2.0] linux
```

## Reason and Possible fixes

If you know or suspect the reason for this bug, paste the code lines and suggest modifications.

## Checklist

- [x] I have checked that there is no similar issue in the repo (**required**)
- [x ] I have read the [documentation](https://github.com/pytorch/rl/tree/main/docs/) (**required**)
- [ x] I have provided a minimal working example to reproduce the bug (**required**)

**Comment by vmoens** [comment]
So just an update on this
I still don't see how I can both make sphinx_gallery happy (since it doesn't want a `if __name__ == "__main__"` at the beginning of the file) and make the script runnable naively.
One ugly solution is to check at the start if we're running in sphinx and if not, make a terrible copy paste of the file content under the if block and call `exec` on that edited script, but that means that things like debugger etc won't work...

We could also edit all the scripts that use parallel stuff and make them runnable naively but that will add a lot of boilerplate that will make the flow much harder to follow...

**Comment by vmoens** [comment]
#1826 should have solved this!
