### ISSUE TITLE
[Feature Request] Why have mutually exclusive terminated and truncated?

### ISSUE THREAD

**Issue by skandermoalla** [pytorch/rl#1899]
truncated and terminated seem to be mutually exclusive in the design of TorchRL. As in this line
https://github.com/pytorch/rl/blob/1bd5ec640a4a37cbb95c402df91b199c9a8b1736/torchrl/envs/transforms/transforms.py#L5183
Is that necessary? IMO this should not be enforced and the truncated signal can still safely be set while the terminated signal is true, which will allow a more faithful status of the trajectory (it was supposed to be truncated but it was incidentally terminated).
This should be safe as components that read terminated (e.g., values estimators) don't need truncated and should ignore it (truncated sets done and then becomes useless in that case.)

This would allow for example to set the truncation key to terminated when one wants to consider finite-horizon environments.
`StepCounter(truncated_key="terminated")`.
 An alternative would be to have something like a `FiniteHorizonTransform` that sets termination based on a step limit.

Happy to hear your thoughts.

**Comment by vmoens** [comment]
Sure I'm open to this change. I recall having seen something exclusive like that somewhere in gymnasium but I can't find it now so it may just be my imagination...
If StepCounter does the job OOB do we need a new transform? Transforms are costly (in terms of maintenance but also in pure monetary terms since we need to test them in every PR and tests take a long time bc we need to check they work in parallel envs). My take would be to find a way of documenting this in a very clear manner and use StepCounter instead. 
Alternatively we could write `FiniteHorizonTransform` as a thin wrapper around `StepCounter` with the truncated key predefined as you mentioned.

**Comment by skandermoalla** [comment]
If truncated and terminated don't need to be exclusive (would need to remove that line from the StepCounter and elsewhere to remove the design choice), then `StepCounter(truncated_key="terminated")` would work OOB and that would be enough yes.

**Comment by vmoens** [comment]
@matteobettini this could be of interest btw

**Comment by matteobettini** [comment]
Yes I agree, this is a good point.

**Comment by matteobettini** [comment]
Very cool that the transform is not tied to truncation only anymore

**Comment by vmoens** [comment]
I'm not following the last comment sorry, can you explain?

**Comment by matteobettini** [comment]
In `StepCounter(truncated_key="terminated")`, `truncated_key` might need renaming if now it can take on more purposes than truncation

**Comment by vmoens** [comment]
I think three names for roughly similar concepts like truncated, terminated and done is already confusing enough haha
