### ISSUE TITLE
[BUG] Compatibility of shapes TanhNormal vs Normal in log prob.

### ISSUE THREAD

**Issue by andreamiele** [pytorch/rl#1933]
## Describe the bug

Compatibility of shapes TanhNormal vs Normal in log prob.

## To Reproduce

```python
import torchrl
loc = torch.zeros(1)
scale = torch.ones(1)
normal = Normal(loc=loc, scale=scale)
tanhnormal = TanhNormal(loc=loc, scale=scale, min=-minmax, max=minmax)
x = tanhnormal.sample((1000,))
n = normal.log_prob(x)
t = tanh_normal.log_prob(x)
print(n.shape)
print(t.shape)
```

```bash
torch.Size([1000, 1])
torch.Size([1000])
```

## Expected behavior

Same shape between the two tensors.

## System info

```python
import torchrl, numpy, sys
print(torchrl.__version__, numpy.__version__, sys.version, sys.platform)
```
```bash
0.4.0+2cfd9b6 1.24.4 3.10.12
```

## Checklist

- [X] I have checked that there is no similar issue in the repo (**required**)
- [X] I have read the [documentation](https://github.com/pytorch/rl/tree/main/docs/) (**required**)
- [X] I have provided a minimal working example to reproduce the bug (**required**)

**Comment by vmoens** [comment]
This is because TanhNormal builds an `Independent(Normal)` base distribution:
https://github.com/pytorch/rl/blob/d68a900ed95a81c32ecf41e7bcdbb8629d618d63/torchrl/modules/distributions/continuous.py#L407

We could make this optional via a kwarg in constructor (and document it better) if you think that could help!

The goal here was to use this for SAC and PPO without requiring the users to pass the dist within an Independent which can be annoying and repetitive.

**Comment by andreamiele** [comment]
cc @skandermoalla

**Comment by matteobettini** [comment]
TorchRL also has an `IndependentNormal` premade for you. This has the same shapes as `TanhNormal `
