### ISSUE TITLE
[BUG] `InitTracker` key flexibility

### ISSUE THREAD

**Issue by matteobettini** [pytorch/rl#2326]
Two questions about the following code 

https://github.com/pytorch/rl/blob/0063741839a3e5e1a527947945494d54f91bc629/torchrl/envs/transforms/transforms.py#L6437-L6440

- is there a reason why we are preventing the `init_key` to be a nested key
- is the setting of `self.reset_key` done properly/ever used? it seems not

**Comment by vmoens** [comment]
For 1)
IIRC yes there was, because we assume that the done is at the root and that the root batch-size is indicative of the env structure.
What would it mean to have a nested `"init"`?
Happy to see a refactoring if it is well defined.

For 2) I don't know, if the value isn't used anywhere we can remove it

**Comment by matteobettini** [comment]
The transform seems to be ok with multiple reset and init keys (the only thing it needs to do is just match an init key for any reset key)

It is just the init method that needs some refreshing I think.
