### ISSUE TITLE
[Clarification] `ParallelEnv` and `_MultiDataCollector`

### ISSUE THREAD

**Issue by matteobettini** [pytorch/rl#809]
Currently there is the option to distribute the sampling phase on different processes using the `ParallelEnv` and `_MultiDataCollector` classes. 

My question is: 
are these two paradigm alternative? 
Or is using only one of them stricly faster? 
What are the advantages of each? 

I would imagine that having one collector with N parallel envs requires only one forward pass of the policy per timestep, while having the sampling divided among M collectors will require M forward passes of the policy.

**Comment by vmoens** [comment]
Thanks for posting this. 
These are compatible tools, not alternatives.
Here's how it works:
`ParallelEnv` just executes `step` and `reset` on spawn processes. It does not interact with the policy (except for the `rollout` method).

The collectors take an environment (or several) and collects rollouts for you.
There are three types:
- `SyncData` collector: executes everything on the same process. 
- `MultiaSyncDataCollector`: launches as many procs as there are envs provided. In each, it runs a separate `SyncDataCollector` and returns the results with a first-comes-first-served async method
- `MultiSyncDataCollector`: launches as many procs as there are envs provided. In each, it runs a separate `SyncDataCollector` and returns the stack of the results collected in each proc

With the collectors, you can tell how much data you want in each batch, how long the trajectories should be, what is the total number of frames that you want to collect before reaching a `StopIteration` etc. Another big advantage is that (unlike what ParallelEnv offers) you can run the separate processes on separate devices. This can dramatically speed things up if you have heavy cuda operations during collection.
Finally, the collectors will separate the batches collected since the reset may differ on different processes. In other words, if you want it (`split_traj=True`) you can get padded trajectories returned to you.

In each, the policy is executed on the tensordict just collected (if the env is batched, you will benefit from vectorization).
e.g.
```python
kwargs = {"total_frames": 1_000_000, "frames_per_batch": 128}

# the simplest collector: 1 env
collector = SyncDataCollector(lambda: GymEnv("Pendulum-v1"), RandomPolicy(action_spec), **kwargs)

for data in collector:
    print(data)
    break

# A multiprocess collector: 2 envs
collector = MultiaSyncDataCollector([lambda: GymEnv("Pendulum-v1")] * 2, RandomPolicy(action_spec), **kwargs)

for data in collector:
    print(data)
    break

# A multiprocess collector, where each process launches its own ParallelEnv: 2 * 4 envs = 8 envs
collector = MultiaSyncDataCollector([ParallelEnv(4, lambda: GymEnv("Pendulum-v1"))] * 2, RandomPolicy(action_spec), **kwargs)

for data in collector:
    print(data)
    break

# A multiprocess collector, where each process launches its own ParallelEnv on a separate device: 2 * 4 envs = 8 envs
collector = MultiaSyncDataCollector([ParallelEnv(4, lambda: GymEnv("Pendulum-v1"))] * 2, RandomPolicy(action_spec), devices=["cuda:0", "cuda:1"], passing_device=["cuda:0", "cuda:1"], **kwargs)

for data in collector:
    print(data)
    break

```

In this way, you can fine tune your collection to take the maximum advantage of the processes you have. 

In our benchmarks, this way of splitting the responsibilities provides important speed-ups in data collection (2-4x for Atari games for instance, 1.5-2x for habitat etc).

**Comment by vmoens** [comment]
We should document this better. I will check that this is explicitly written in the doc.

**Comment by matteobettini** [comment]
Thanks for the clarifications!
